///////////////////////////////////////////////////////////
//  Requests.cs
//  Implementation of the Class Requests
//  Generated by Enterprise Architect
//  Created on:      26-nov-2022 12:20:07
//  Original author: Skole
///////////////////////////////////////////////////////////

namespace Webmanager.Webmanager
{
	internal class Requests : IRequests
	{


		public Requests()
		{

		}

		~Requests()
		{

		}

		public void Post()
		{

		}

		public void Put()
		{

		}

		public void Delete()
		{

		}

		public void Get()
		{

		}

	}//end Requests

}//end namespace Webmanager