///////////////////////////////////////////////////////////
//  GroupParser.cs
//  Implementation of the Class GroupParser
//  Generated by Enterprise Architect
//  Created on:      26-nov-2022 12:13:28
//  Original author: Lars
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Docmanager;
using System.Runtime.CompilerServices;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using System.Text.RegularExpressions;


namespace Docmanager
{
    internal class Docmanager : IDocmanager
    {
        //Fetch and derealize json file
        const string filepath = @"E:\Dataing\IKT300\Engineering units - mappe eksamen\Docmanager\POSC.json";
        List<Root> jsonDeserialized = JsonConvert.DeserializeObject<List<Root>>(File.ReadAllText(filepath));

        public string ReadAnnotation(string unitName)
        {
            Root match =
                (from unit in jsonDeserialized
                 where unit.Name == unitName
                 select unit).First();

            try
            {
                return match.annotation;
            }
            catch (NullReferenceException) {return "";}
            
            return "";
        }

        public void ReadConversion(string unitName, ref double A, ref double B, ref double C, ref double D) 
        {
            A = 0; B = 0; C = 0; D = 0;

            Root match =
                (from unit in jsonDeserialized
                 where unit.Name == unitName
                 select unit).First();

            try
            {
                if (match.ConversionToBaseUnit.baseUnit != null)
                {
                    C = 1;
                }
            } catch (NullReferenceException) { }

            try 
            {
                if (match.ConversionToBaseUnit.Formula.A != null)
                {
                    A = double.Parse(match.ConversionToBaseUnit.Formula.A);
                }
            } catch (NullReferenceException) { }

            try 
            {
                if (match.ConversionToBaseUnit.Formula.B != null)
                {
                    B = double.Parse(match.ConversionToBaseUnit.Formula.B);
                }
            }
            catch (NullReferenceException) { }

            try 
            {
                if (match.ConversionToBaseUnit.Formula.C != null)
                {
                    C = double.Parse(match.ConversionToBaseUnit.Formula.C);
                }
            }
            catch (NullReferenceException) { }

            try 
            {
                if (match.ConversionToBaseUnit.Formula.D != null)
                {
                    D = double.Parse(match.ConversionToBaseUnit.Formula.D);
                }
            }
            catch (NullReferenceException) { }

            try 
            {
                if (match.ConversionToBaseUnit.Factor != null)
                {
                    B = double.Parse(match.ConversionToBaseUnit.Factor);
                }
            } catch (NullReferenceException) { }

            try 
            {
                if (match.ConversionToBaseUnit.Fraction.Numerator != null)
                {
                    B = double.Parse(match.ConversionToBaseUnit.Fraction.Numerator);
                }
            } catch (NullReferenceException) { }
            
            try
            {
                if (match.ConversionToBaseUnit.Fraction.Denominator != null)
                {
                    C = double.Parse(match.ConversionToBaseUnit.Fraction.Denominator);
                }
            } catch (NullReferenceException) { }
        }
        public void CreateUOM(string id, string annotation, string name, string quantityType, string dimensionalclass, string baseunit)
        {
            String newUnitString =
                "{" +
                    "\"id\": null," +
                    "\"annotation\": null," +
                    "\"Name\": null," +
                    "\"QuantityType\": null," +
                    "\"DimensionalClass\": null," +
                    "\"SameUnit\": {" +
                      "\"uom\": null," +
                      "\"namingSystem\": null" +
                    "}," +
                    "\"CatalogName\": null," +
                    "\"CatalogSymbol\": {" +
                      "\"isExplicit\": null," +
                      "\"text\": null" +
                    "}," +
                    "\"ConversionToBaseUnit\": {" +
                      "\"baseUnit\": null," +
                      "\"Formula\": {" +
                        "\"A\": null," +
                        "\"B\": null," +
                        "\"C\": null," +
                        "\"D\": null" +
                      "}" +
                    "}" +
                "}";

            Root newUnitDeserialized = JsonConvert.DeserializeObject<Root>(newUnitString);

            newUnitDeserialized.id = id;
            newUnitDeserialized.annotation = annotation;
            newUnitDeserialized.Name = name;
            newUnitDeserialized.QuantityType = quantityType;
            newUnitDeserialized.DimensionalClass = dimensionalclass;
            newUnitDeserialized.ConversionToBaseUnit.baseUnit = baseunit;

            jsonDeserialized.Add(newUnitDeserialized);

            string output = JsonConvert.SerializeObject(jsonDeserialized, Formatting.Indented);

            File.WriteAllText(filepath, output);
        }
        public void EditUOM(string old_id, string id, string annotation, string name, string qualitytype, string dimensionalclass, string baseunit)
        {
            Root match =
                (from unit in jsonDeserialized
                 where unit.id == old_id
                 select unit).First();

            match.id = id;
            match.annotation = annotation;
            match.Name = name;
            match.QuantityType = qualitytype;
            match.DimensionalClass = dimensionalclass;
            match.ConversionToBaseUnit.baseUnit = baseunit;

            string output = JsonConvert.SerializeObject(jsonDeserialized, Formatting.Indented);

            File.WriteAllText(filepath, output);
        }
        public void DeleteUOM(string id)
        {
            Root match =
                (from unit in jsonDeserialized
                 where unit.id == id
                 select unit).First();

            jsonDeserialized.Remove(match);

            string output = JsonConvert.SerializeObject(jsonDeserialized, Formatting.Indented);

            File.WriteAllText(filepath, output);
        }
        public class BaseUnit
        {
            public string BasicAuthority { get; set; }
            public string Description { get; set; }
        }

        public class CatalogSymbol
        {
            public string isExplicit { get; set; }
            public string text { get; set; }
        }

        public class ConversionToBaseUnit
        {
            public string baseUnit { get; set; }
            public string Factor { get; set; }
            public Fraction Fraction { get; set; }
            public Formula Formula { get; set; }
        }

        public class Formula
        {
            public string A { get; set; }
            public string B { get; set; }
            public string C { get; set; }
            public string D { get; set; }
        }

        public class Fraction
        {
            public string Numerator { get; set; }
            public string Denominator { get; set; }
        }

        public class Root
        {
            public string id { get; set; }
            public string annotation { get; set; }
            public string Name { get; set; }
            public object QuantityType { get; set; }
            public string DimensionalClass { get; set; }
            public object SameUnit { get; set; }
            public string CatalogName { get; set; }
            public CatalogSymbol CatalogSymbol { get; set; }
            public BaseUnit BaseUnit { get; set; }
            public string Deprecated { get; set; }
            public ConversionToBaseUnit ConversionToBaseUnit { get; set; }
        }




    }//end GroupParser

}//end namespace Docmanager