///////////////////////////////////////////////////////////
//  Factory.cs
//  Implementation of the Class Factory
//  Generated by Enterprise Architect
//  Created on:      26-nov-2022 12:23:52
//  Original author: Skole
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Connector;
using Converter.Connector;

namespace Connector {
	public class Factory : IConnector {

		public Factory(){

		}

		~Factory(){

		}

		public void CreateGroupManager(){

		}

		public void CreateUnitManager(){

		}

	}//end Factory

}//end namespace Connector