///////////////////////////////////////////////////////////
//  GroupManager.cs
//  Implementation of the Class GroupManager
//  Generated by Enterprise Architect
//  Created on:      26-nov-2022 12:21:30
//  Original author: Skole
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Connector;
using Docmanager;
using Converter.Connector;

namespace Connector {
	internal class GroupManager : IConnector {

		public GroupManager(){

		}

		~GroupManager(){

		}

		public void CreateGroup(){


		}

		public void EditGroup(){

		}

		public void DeleteGroup(){

		}

		public void AddUnit(){

		}

		public void RemoveUnit(){

		}

		public void ListGroups(){

		}

		public void ReadGroup(){

		}

	}//end GroupManager

}//end namespace Connector