///////////////////////////////////////////////////////////
//  GroupManager.cs
//  Implementation of the Class GroupManager
//  Generated by Enterprise Architect
//  Created on:      26-nov-2022 12:21:30
//  Original author: Skole
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Connector;
using Docmanager;
using Converter.Connector;
using System.Security.Cryptography.X509Certificates;

namespace Connector {
	internal class Connector : IC {
		public Tuple<double, string, string> BaseToConvert(double value, string unitFrom, string unitTo)
		{
			throw new NotImplementedException();
		}


		public Tuple<double, string, string> ConvertToBase(double value, string unitFrom, string unitTo)
		{
			throw new NotImplementedException();
		}

		public string WriteToConsole(Tuple<double, string, string> tuple)
		{
			throw new NotImplementedException();
		}
	}



	}//end GroupManager

