///////////////////////////////////////////////////////////
//  UnitManager.cs
//  Implementation of the Class UnitManager
//  Generated by Enterprise Architect
//  Created on:      26-nov-2022 12:21:32
//  Original author: Skole
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Connector;
using Docmanager;
namespace Connector {
	internal class UnitManager : IConnector {

		public UnitManager(){

		}

		~UnitManager(){

		}

		public void CreateUnit(){

		}

		public void EditUnit(){

		}

		public void ConvertUnit(){

		}

		public void DeleteUnit(){

		}

		public void ListUnits(){

		}

		public void ReadUnit(){

		}

	}//end UnitManager

}//end namespace Connector