///////////////////////////////////////////////////////////
//  Requests.cs
//  Implementation of the Class Requests
//  Generated by Enterprise Architect
//  Created on:      26-nov-2022 12:20:07
//  Original author: Skole
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Connector;
using Webmanager;
namespace Webmanager {
	internal class Requests : IRequests {

		public Not in use(Factory) m_Not in use(Factory);

		public Requests(){

		}

		~Requests(){

		}

		public void Post(){

		}

		public void Put(){

		}

		public void Delete(){

		}

		public void Get(){

		}

	}//end Requests

}//end namespace Webmanager