///////////////////////////////////////////////////////////
//  Factory.cs
//  Implementation of the Class Factory
//  Generated by Enterprise Architect
//  Created on:      26-nov-2022 12:13:25
//  Original author: Skole
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Converter.Docmanager
{
    public class Factory : IDocmanager
    {

        public Factory()
        {

        }

        ~Factory()
        {

        }

        public void CreateGroupParser()
        {

        }

        public void CreateUnitParser()
        {

        }

    }//end Factory

}//end namespace Docmanager