///////////////////////////////////////////////////////////
//  Factory.cs
//  Implementation of the Class Factory
//  Generated by Enterprise Architect
//  Created on:      26-nov-2022 12:13:25
//  Original author: Skole
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Docmanager;

namespace Converter.Docmanager
{
    public class Factory 
    {

        public static IDocmanager Create(string name)
        {


            IPSU psu = null;

            if (name.ToUpper() == "PS2000")
                psu = new Ps2000();
            else if (name == "Ps3000")
                psu = new Ps3000();
            else if (name == "Test")
                psu = new TestPsu();
            return psu;
        }




    }//end Factory

}//end namespace Docmanager