///////////////////////////////////////////////////////////
//  Group.cs
//  Implementation of the Class Group
//  Generated by Enterprise Architect
//  Created on:      27-nov-2022 14:10:04
//  Original author: Skole
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Docmanager;
namespace Docmanager {
	public class Group {

		public string _name;
		public string _baseUnit;
		public List<Unitd> Units;
		

	}//end Group

}//end namespace Docmanager