///////////////////////////////////////////////////////////
//  GroupParser.cs
//  Implementation of the Class GroupParser
//  Generated by Enterprise Architect
//  Created on:      26-nov-2022 12:13:28
//  Original author: Lars
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Docmanager;
using Converter.Docmanager;

namespace Docmanager {
	internal class GroupParser : IDocmanager {

		public GroupParser(){

		}

		~GroupParser(){

		}

		public void CreateUnit(){

		}

		public void EditUnit(){

		}

		public void DeleteUnit(){

		}

		public void ListUnits(){

		}

		public void GetUnit(){

		}

	}//end GroupParser

}//end namespace Docmanager