///////////////////////////////////////////////////////////
//  GroupParser.cs
//  Implementation of the Class GroupParser
//  Generated by Enterprise Architect
//  Created on:      26-nov-2022 12:13:28
//  Original author: Lars
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Docmanager;
using Converter.Docmanager;

namespace Docmanager {
	internal class Parser : IDocmanager {


        string _name;
        string _baseUnit;
        string[] _units;
        


        public void EditGroup(string? newName, string baseUnit, string[]? units)
        {
            throw new NotImplementedException();
        }

        public void DeleteGroup(string name)
        {
            throw new NotImplementedException();
        }

        public void AddUnit(string unitName)
        {
            throw new NotImplementedException();
        }

        public void RemoveUnit(string name)
        {
            throw new NotImplementedException();
        }

        string[] IDocmanager.ListGroups()
        {
            throw new NotImplementedException();
        }

        IDocmanager IDocmanager.ReadGroup()
        {
            throw new NotImplementedException();
        }

        public int CreateUnit(string name, string si, double[] value)
        {
            throw new NotImplementedException();
        }

        public int EditUnit(string? newName, string? si, double[]? value)
        {
            throw new NotImplementedException();
        }

        public int DeleteUnit(string name)
        {
            throw new NotImplementedException();
        }

        public string[] ListUnits()
        {
            throw new NotImplementedException();
        }

        public IDocmanager GetUnit()
        {
            throw new NotImplementedException();
        }
    }//end GroupParser

}//end namespace Docmanager