///////////////////////////////////////////////////////////
//  Unit.cs
//  Implementation of the Class Unit
//  Generated by Enterprise Architect
//  Created on:      27-nov-2022 14:10:02
//  Original author: Skole
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Docmanager;
namespace Docmanager {
	public class Unitd {

		public string _name;
		public string _SI;
		public double _A;
		public double _B;
		public double _C;
		public double _D;
		

	}//end Unit

}//end namespace Docmanager