///////////////////////////////////////////////////////////
//  UnitParser.cs
//  Implementation of the Class UnitParser
//  Generated by Enterprise Architect
//  Created on:      26-nov-2022 12:13:38
//  Original author: Skole
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Docmanager;
using Converter.Docmanager;

namespace Docmanager {
	internal class UnitParser : IDocmanager {

		public UnitParser(){

		}

		~UnitParser(){

		}

		public void EditGroup(){

		}

		public void DeleteGroup(){

		}

		public void AddUnit(){

		}

		public void RemoveUnit(){

		}

		public void ListGroups(){

		}

		public void ReadGroup(){

		}

	}//end UnitParser

}//end namespace Docmanager